// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Elasticstack
{
    public static class ElasticsearchIngestProcessorUserAgent
    {
        /// <summary>
        /// The `user_agent` processor extracts details from the user agent string a browser sends with its web requests. This processor adds this information by default under the `user_agent` field.
        /// 
        /// The ingest-user-agent module ships by default with the regexes.yaml made available by uap-java with an Apache 2.0 license. For more details see https://github.com/ua-parser/uap-core.
        /// 
        /// 
        /// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/user-agent-processor.html
        /// 
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Elasticstack = Pulumi.Elasticstack;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var agent = Output.Create(Elasticstack.ElasticsearchIngestProcessorUserAgent.InvokeAsync(new Elasticstack.ElasticsearchIngestProcessorUserAgentArgs
        ///         {
        ///             Field = "agent",
        ///         }));
        ///         var myIngestPipeline = new Elasticstack.ElasticsearchIngestPipeline("myIngestPipeline", new Elasticstack.ElasticsearchIngestPipelineArgs
        ///         {
        ///             Processors = 
        ///             {
        ///                 agent.Apply(agent =&gt; agent.Json),
        ///             },
        ///         });
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<ElasticsearchIngestProcessorUserAgentResult> InvokeAsync(ElasticsearchIngestProcessorUserAgentArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<ElasticsearchIngestProcessorUserAgentResult>("elasticstack:index/elasticsearchIngestProcessorUserAgent:ElasticsearchIngestProcessorUserAgent", args ?? new ElasticsearchIngestProcessorUserAgentArgs(), options.WithDefaults());

        /// <summary>
        /// The `user_agent` processor extracts details from the user agent string a browser sends with its web requests. This processor adds this information by default under the `user_agent` field.
        /// 
        /// The ingest-user-agent module ships by default with the regexes.yaml made available by uap-java with an Apache 2.0 license. For more details see https://github.com/ua-parser/uap-core.
        /// 
        /// 
        /// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/user-agent-processor.html
        /// 
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Elasticstack = Pulumi.Elasticstack;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var agent = Output.Create(Elasticstack.ElasticsearchIngestProcessorUserAgent.InvokeAsync(new Elasticstack.ElasticsearchIngestProcessorUserAgentArgs
        ///         {
        ///             Field = "agent",
        ///         }));
        ///         var myIngestPipeline = new Elasticstack.ElasticsearchIngestPipeline("myIngestPipeline", new Elasticstack.ElasticsearchIngestPipelineArgs
        ///         {
        ///             Processors = 
        ///             {
        ///                 agent.Apply(agent =&gt; agent.Json),
        ///             },
        ///         });
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<ElasticsearchIngestProcessorUserAgentResult> Invoke(ElasticsearchIngestProcessorUserAgentInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<ElasticsearchIngestProcessorUserAgentResult>("elasticstack:index/elasticsearchIngestProcessorUserAgent:ElasticsearchIngestProcessorUserAgent", args ?? new ElasticsearchIngestProcessorUserAgentInvokeArgs(), options.WithDefaults());
    }


    public sealed class ElasticsearchIngestProcessorUserAgentArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// Extracts device type from the user agent string on a best-effort basis. Supported only starting from Elasticsearch version **8.0**
        /// </summary>
        [Input("extractDeviceType")]
        public bool? ExtractDeviceType { get; set; }

        /// <summary>
        /// The field containing the user agent string.
        /// </summary>
        [Input("field", required: true)]
        public string Field { get; set; } = null!;

        /// <summary>
        /// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
        /// </summary>
        [Input("ignoreMissing")]
        public bool? IgnoreMissing { get; set; }

        [Input("properties")]
        private List<string>? _properties;

        /// <summary>
        /// Controls what properties are added to `target_field`.
        /// </summary>
        public List<string> Properties
        {
            get => _properties ?? (_properties = new List<string>());
            set => _properties = value;
        }

        /// <summary>
        /// The name of the file in the `config/ingest-user-agent` directory containing the regular expressions for parsing the user agent string.
        /// </summary>
        [Input("regexFile")]
        public string? RegexFile { get; set; }

        /// <summary>
        /// The field that will be filled with the user agent details.
        /// </summary>
        [Input("targetField")]
        public string? TargetField { get; set; }

        public ElasticsearchIngestProcessorUserAgentArgs()
        {
        }
    }

    public sealed class ElasticsearchIngestProcessorUserAgentInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// Extracts device type from the user agent string on a best-effort basis. Supported only starting from Elasticsearch version **8.0**
        /// </summary>
        [Input("extractDeviceType")]
        public Input<bool>? ExtractDeviceType { get; set; }

        /// <summary>
        /// The field containing the user agent string.
        /// </summary>
        [Input("field", required: true)]
        public Input<string> Field { get; set; } = null!;

        /// <summary>
        /// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
        /// </summary>
        [Input("ignoreMissing")]
        public Input<bool>? IgnoreMissing { get; set; }

        [Input("properties")]
        private InputList<string>? _properties;

        /// <summary>
        /// Controls what properties are added to `target_field`.
        /// </summary>
        public InputList<string> Properties
        {
            get => _properties ?? (_properties = new InputList<string>());
            set => _properties = value;
        }

        /// <summary>
        /// The name of the file in the `config/ingest-user-agent` directory containing the regular expressions for parsing the user agent string.
        /// </summary>
        [Input("regexFile")]
        public Input<string>? RegexFile { get; set; }

        /// <summary>
        /// The field that will be filled with the user agent details.
        /// </summary>
        [Input("targetField")]
        public Input<string>? TargetField { get; set; }

        public ElasticsearchIngestProcessorUserAgentInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class ElasticsearchIngestProcessorUserAgentResult
    {
        /// <summary>
        /// Extracts device type from the user agent string on a best-effort basis. Supported only starting from Elasticsearch version **8.0**
        /// </summary>
        public readonly bool? ExtractDeviceType;
        /// <summary>
        /// The field containing the user agent string.
        /// </summary>
        public readonly string Field;
        /// <summary>
        /// Internal identifier of the resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
        /// </summary>
        public readonly bool? IgnoreMissing;
        /// <summary>
        /// JSON representation of this data source.
        /// </summary>
        public readonly string Json;
        /// <summary>
        /// Controls what properties are added to `target_field`.
        /// </summary>
        public readonly ImmutableArray<string> Properties;
        /// <summary>
        /// The name of the file in the `config/ingest-user-agent` directory containing the regular expressions for parsing the user agent string.
        /// </summary>
        public readonly string? RegexFile;
        /// <summary>
        /// The field that will be filled with the user agent details.
        /// </summary>
        public readonly string? TargetField;

        [OutputConstructor]
        private ElasticsearchIngestProcessorUserAgentResult(
            bool? extractDeviceType,

            string field,

            string id,

            bool? ignoreMissing,

            string json,

            ImmutableArray<string> properties,

            string? regexFile,

            string? targetField)
        {
            ExtractDeviceType = extractDeviceType;
            Field = field;
            Id = id;
            IgnoreMissing = ignoreMissing;
            Json = json;
            Properties = properties;
            RegexFile = regexFile;
            TargetField = targetField;
        }
    }
}
