// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Elasticstack.Outputs
{

    [OutputType]
    public sealed class ElasticsearchClusterSettingsTransient
    {
        /// <summary>
        /// Defines the setting in the cluster.
        /// </summary>
        public readonly ImmutableArray<Outputs.ElasticsearchClusterSettingsTransientSetting> Settings;

        [OutputConstructor]
        private ElasticsearchClusterSettingsTransient(ImmutableArray<Outputs.ElasticsearchClusterSettingsTransientSetting> settings)
        {
            Settings = settings;
        }
    }
}
