// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Elasticstack.Outputs
{

    [OutputType]
    public sealed class ElasticsearchIndexLifecycleFrozen
    {
        /// <summary>
        /// ILM moves indices through the lifecycle according to their age. To control the timing of these transitions, you set a minimum age for each phase.
        /// </summary>
        public readonly string? MinAge;
        /// <summary>
        /// Takes a snapshot of the managed index in the configured repository and mounts it as a searchable snapshot.
        /// </summary>
        public readonly Outputs.ElasticsearchIndexLifecycleFrozenSearchableSnapshot? SearchableSnapshot;

        [OutputConstructor]
        private ElasticsearchIndexLifecycleFrozen(
            string? minAge,

            Outputs.ElasticsearchIndexLifecycleFrozenSearchableSnapshot? searchableSnapshot)
        {
            MinAge = minAge;
            SearchableSnapshot = searchableSnapshot;
        }
    }
}
