// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Elasticstack.Outputs
{

    [OutputType]
    public sealed class ElasticsearchIndexLifecycleDelete
    {
        /// <summary>
        /// Permanently removes the index.
        /// </summary>
        public readonly Outputs.ElasticsearchIndexLifecycleDeleteDelete? Delete;
        /// <summary>
        /// ILM moves indices through the lifecycle according to their age. To control the timing of these transitions, you set a minimum age for each phase.
        /// </summary>
        public readonly string? MinAge;
        /// <summary>
        /// Waits for the specified SLM policy to be executed before removing the index. This ensures that a snapshot of the deleted index is available.
        /// </summary>
        public readonly Outputs.ElasticsearchIndexLifecycleDeleteWaitForSnapshot? WaitForSnapshot;

        [OutputConstructor]
        private ElasticsearchIndexLifecycleDelete(
            Outputs.ElasticsearchIndexLifecycleDeleteDelete? delete,

            string? minAge,

            Outputs.ElasticsearchIndexLifecycleDeleteWaitForSnapshot? waitForSnapshot)
        {
            Delete = delete;
            MinAge = minAge;
            WaitForSnapshot = waitForSnapshot;
        }
    }
}
