// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Elasticstack.Inputs
{

    public sealed class ElasticsearchClusterSettingsPersistentArgs : Pulumi.ResourceArgs
    {
        [Input("settings", required: true)]
        private InputList<Inputs.ElasticsearchClusterSettingsPersistentSettingArgs>? _settings;

        /// <summary>
        /// Defines the setting in the cluster.
        /// </summary>
        public InputList<Inputs.ElasticsearchClusterSettingsPersistentSettingArgs> Settings
        {
            get => _settings ?? (_settings = new InputList<Inputs.ElasticsearchClusterSettingsPersistentSettingArgs>());
            set => _settings = value;
        }

        public ElasticsearchClusterSettingsPersistentArgs()
        {
        }
    }
}
