// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Expands a field with dots into an object field. This processor allows fields with dots in the name to be accessible by other processors in the pipeline. Otherwise these fields can’t be accessed by any processor.
//
// See: elastic.co/guide/en/elasticsearch/reference/current/dot-expand-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		dotExpander, err := elasticstack.ElasticsearchIngestProcessorDotExpander(ctx, &ElasticsearchIngestProcessorDotExpanderArgs{
// 			Field: "foo.bar",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		_, err = elasticstack.NewElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticsearchIngestPipelineArgs{
// 			Processors: pulumi.StringArray{
// 				pulumi.String(dotExpander.Json),
// 			},
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func ElasticsearchIngestProcessorDotExpander(ctx *pulumi.Context, args *ElasticsearchIngestProcessorDotExpanderArgs, opts ...pulumi.InvokeOption) (*ElasticsearchIngestProcessorDotExpanderResult, error) {
	var rv ElasticsearchIngestProcessorDotExpanderResult
	err := ctx.Invoke("elasticstack:index/elasticsearchIngestProcessorDotExpander:ElasticsearchIngestProcessorDotExpander", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticsearchIngestProcessorDotExpander.
type ElasticsearchIngestProcessorDotExpanderArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to expand into an object field. If set to *, all top-level fields will be expanded.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Controls the behavior when there is already an existing nested object that conflicts with the expanded field.
	Override *bool `pulumi:"override"`
	// The field that contains the field to expand.
	Path *string `pulumi:"path"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
}

// A collection of values returned by ElasticsearchIngestProcessorDotExpander.
type ElasticsearchIngestProcessorDotExpanderResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to expand into an object field. If set to *, all top-level fields will be expanded.
	Field string `pulumi:"field"`
	// Internal identifier of the resource
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Controls the behavior when there is already an existing nested object that conflicts with the expanded field.
	Override *bool `pulumi:"override"`
	// The field that contains the field to expand.
	Path *string `pulumi:"path"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
}

func ElasticsearchIngestProcessorDotExpanderOutput(ctx *pulumi.Context, args ElasticsearchIngestProcessorDotExpanderOutputArgs, opts ...pulumi.InvokeOption) ElasticsearchIngestProcessorDotExpanderResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticsearchIngestProcessorDotExpanderResult, error) {
			args := v.(ElasticsearchIngestProcessorDotExpanderArgs)
			r, err := ElasticsearchIngestProcessorDotExpander(ctx, &args, opts...)
			return *r, err
		}).(ElasticsearchIngestProcessorDotExpanderResultOutput)
}

// A collection of arguments for invoking ElasticsearchIngestProcessorDotExpander.
type ElasticsearchIngestProcessorDotExpanderOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to expand into an object field. If set to *, all top-level fields will be expanded.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Controls the behavior when there is already an existing nested object that conflicts with the expanded field.
	Override pulumi.BoolPtrInput `pulumi:"override"`
	// The field that contains the field to expand.
	Path pulumi.StringPtrInput `pulumi:"path"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
}

func (ElasticsearchIngestProcessorDotExpanderOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorDotExpanderArgs)(nil)).Elem()
}

// A collection of values returned by ElasticsearchIngestProcessorDotExpander.
type ElasticsearchIngestProcessorDotExpanderResultOutput struct{ *pulumi.OutputState }

func (ElasticsearchIngestProcessorDotExpanderResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorDotExpanderResult)(nil)).Elem()
}

func (o ElasticsearchIngestProcessorDotExpanderResultOutput) ToElasticsearchIngestProcessorDotExpanderResultOutput() ElasticsearchIngestProcessorDotExpanderResultOutput {
	return o
}

func (o ElasticsearchIngestProcessorDotExpanderResultOutput) ToElasticsearchIngestProcessorDotExpanderResultOutputWithContext(ctx context.Context) ElasticsearchIngestProcessorDotExpanderResultOutput {
	return o
}

// Description of the processor.
func (o ElasticsearchIngestProcessorDotExpanderResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDotExpanderResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to expand into an object field. If set to *, all top-level fields will be expanded.
func (o ElasticsearchIngestProcessorDotExpanderResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDotExpanderResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource
func (o ElasticsearchIngestProcessorDotExpanderResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDotExpanderResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticsearchIngestProcessorDotExpanderResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDotExpanderResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticsearchIngestProcessorDotExpanderResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDotExpanderResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticsearchIngestProcessorDotExpanderResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDotExpanderResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o ElasticsearchIngestProcessorDotExpanderResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDotExpanderResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Controls the behavior when there is already an existing nested object that conflicts with the expanded field.
func (o ElasticsearchIngestProcessorDotExpanderResultOutput) Override() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDotExpanderResult) *bool { return v.Override }).(pulumi.BoolPtrOutput)
}

// The field that contains the field to expand.
func (o ElasticsearchIngestProcessorDotExpanderResultOutput) Path() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDotExpanderResult) *string { return v.Path }).(pulumi.StringPtrOutput)
}

// Identifier for the processor.
func (o ElasticsearchIngestProcessorDotExpanderResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDotExpanderResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticsearchIngestProcessorDotExpanderResultOutput{})
}
