// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Converts a JSON string into a structured JSON object.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/json-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := "json_target"
// 		jsonProc, err := elasticstack.ElasticsearchIngestProcessorJson(ctx, &ElasticsearchIngestProcessorJsonArgs{
// 			Field:       "string_source",
// 			TargetField: &opt0,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		_, err = elasticstack.NewElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticsearchIngestPipelineArgs{
// 			Processors: pulumi.StringArray{
// 				pulumi.String(jsonProc.Json),
// 			},
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func ElasticsearchIngestProcessorJson(ctx *pulumi.Context, args *ElasticsearchIngestProcessorJsonArgs, opts ...pulumi.InvokeOption) (*ElasticsearchIngestProcessorJsonResult, error) {
	var rv ElasticsearchIngestProcessorJsonResult
	err := ctx.Invoke("elasticstack:index/elasticsearchIngestProcessorJson:ElasticsearchIngestProcessorJson", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticsearchIngestProcessorJson.
type ElasticsearchIngestProcessorJsonArgs struct {
	// Flag that forces the parsed JSON to be added at the top level of the document. `targetField` must not be set when this option is chosen.
	AddToRoot *bool `pulumi:"addToRoot"`
	// When set to `replace`, root fields that conflict with fields from the parsed JSON will be overridden. When set to `merge`, conflicting fields will be merged. Only applicable if `addToRoot` is set to `true`.
	AddToRootConflictStrategy *string `pulumi:"addToRootConflictStrategy"`
	// When set to `true`, the JSON parser will not fail if the JSON contains duplicate keys. Instead, the last encountered value for any duplicate key wins.
	AllowDuplicateKeys *bool `pulumi:"allowDuplicateKeys"`
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to be parsed.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field that the converted structured object will be written into. Any existing content in this field will be overwritten.
	TargetField *string `pulumi:"targetField"`
}

// A collection of values returned by ElasticsearchIngestProcessorJson.
type ElasticsearchIngestProcessorJsonResult struct {
	// Flag that forces the parsed JSON to be added at the top level of the document. `targetField` must not be set when this option is chosen.
	AddToRoot *bool `pulumi:"addToRoot"`
	// When set to `replace`, root fields that conflict with fields from the parsed JSON will be overridden. When set to `merge`, conflicting fields will be merged. Only applicable if `addToRoot` is set to `true`.
	AddToRootConflictStrategy *string `pulumi:"addToRootConflictStrategy"`
	// When set to `true`, the JSON parser will not fail if the JSON contains duplicate keys. Instead, the last encountered value for any duplicate key wins.
	AllowDuplicateKeys *bool `pulumi:"allowDuplicateKeys"`
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to be parsed.
	Field string `pulumi:"field"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field that the converted structured object will be written into. Any existing content in this field will be overwritten.
	TargetField *string `pulumi:"targetField"`
}

func ElasticsearchIngestProcessorJsonOutput(ctx *pulumi.Context, args ElasticsearchIngestProcessorJsonOutputArgs, opts ...pulumi.InvokeOption) ElasticsearchIngestProcessorJsonResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticsearchIngestProcessorJsonResult, error) {
			args := v.(ElasticsearchIngestProcessorJsonArgs)
			r, err := ElasticsearchIngestProcessorJson(ctx, &args, opts...)
			return *r, err
		}).(ElasticsearchIngestProcessorJsonResultOutput)
}

// A collection of arguments for invoking ElasticsearchIngestProcessorJson.
type ElasticsearchIngestProcessorJsonOutputArgs struct {
	// Flag that forces the parsed JSON to be added at the top level of the document. `targetField` must not be set when this option is chosen.
	AddToRoot pulumi.BoolPtrInput `pulumi:"addToRoot"`
	// When set to `replace`, root fields that conflict with fields from the parsed JSON will be overridden. When set to `merge`, conflicting fields will be merged. Only applicable if `addToRoot` is set to `true`.
	AddToRootConflictStrategy pulumi.StringPtrInput `pulumi:"addToRootConflictStrategy"`
	// When set to `true`, the JSON parser will not fail if the JSON contains duplicate keys. Instead, the last encountered value for any duplicate key wins.
	AllowDuplicateKeys pulumi.BoolPtrInput `pulumi:"allowDuplicateKeys"`
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to be parsed.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The field that the converted structured object will be written into. Any existing content in this field will be overwritten.
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
}

func (ElasticsearchIngestProcessorJsonOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorJsonArgs)(nil)).Elem()
}

// A collection of values returned by ElasticsearchIngestProcessorJson.
type ElasticsearchIngestProcessorJsonResultOutput struct{ *pulumi.OutputState }

func (ElasticsearchIngestProcessorJsonResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorJsonResult)(nil)).Elem()
}

func (o ElasticsearchIngestProcessorJsonResultOutput) ToElasticsearchIngestProcessorJsonResultOutput() ElasticsearchIngestProcessorJsonResultOutput {
	return o
}

func (o ElasticsearchIngestProcessorJsonResultOutput) ToElasticsearchIngestProcessorJsonResultOutputWithContext(ctx context.Context) ElasticsearchIngestProcessorJsonResultOutput {
	return o
}

// Flag that forces the parsed JSON to be added at the top level of the document. `targetField` must not be set when this option is chosen.
func (o ElasticsearchIngestProcessorJsonResultOutput) AddToRoot() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) *bool { return v.AddToRoot }).(pulumi.BoolPtrOutput)
}

// When set to `replace`, root fields that conflict with fields from the parsed JSON will be overridden. When set to `merge`, conflicting fields will be merged. Only applicable if `addToRoot` is set to `true`.
func (o ElasticsearchIngestProcessorJsonResultOutput) AddToRootConflictStrategy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) *string { return v.AddToRootConflictStrategy }).(pulumi.StringPtrOutput)
}

// When set to `true`, the JSON parser will not fail if the JSON contains duplicate keys. Instead, the last encountered value for any duplicate key wins.
func (o ElasticsearchIngestProcessorJsonResultOutput) AllowDuplicateKeys() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) *bool { return v.AllowDuplicateKeys }).(pulumi.BoolPtrOutput)
}

// Description of the processor.
func (o ElasticsearchIngestProcessorJsonResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to be parsed.
func (o ElasticsearchIngestProcessorJsonResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource.
func (o ElasticsearchIngestProcessorJsonResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticsearchIngestProcessorJsonResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticsearchIngestProcessorJsonResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticsearchIngestProcessorJsonResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o ElasticsearchIngestProcessorJsonResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Identifier for the processor.
func (o ElasticsearchIngestProcessorJsonResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The field that the converted structured object will be written into. Any existing content in this field will be overwritten.
func (o ElasticsearchIngestProcessorJsonResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorJsonResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticsearchIngestProcessorJsonResultOutput{})
}
