// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Helper data source to which can be used to parse dates from fields, and then uses the date or timestamp as the timestamp for the document.
// By default, the date processor adds the parsed date as a new field called `@timestamp`. You can specify a different field by setting the `targetField` configuration parameter. Multiple date formats are supported as part of the same date processor definition. They will be used sequentially to attempt parsing the date field, in the same order they were defined as part of the processor definition.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/date-processor.html
//
// ## Example Usage
//
// Here is an example that adds the parsed date to the `timestamp` field based on the `initialDate` field:
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := "timestamp"
// 		opt1 := "Europe/Amsterdam"
// 		date, err := elasticstack.ElasticsearchIngestProcessorDate(ctx, &ElasticsearchIngestProcessorDateArgs{
// 			Field:       "initial_date",
// 			TargetField: &opt0,
// 			Formats: []string{
// 				"dd/MM/yyyy HH:mm:ss",
// 			},
// 			Timezone: &opt1,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		_, err = elasticstack.NewElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticsearchIngestPipelineArgs{
// 			Processors: pulumi.StringArray{
// 				pulumi.String(date.Json),
// 			},
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func ElasticsearchIngestProcessorDate(ctx *pulumi.Context, args *ElasticsearchIngestProcessorDateArgs, opts ...pulumi.InvokeOption) (*ElasticsearchIngestProcessorDateResult, error) {
	var rv ElasticsearchIngestProcessorDateResult
	err := ctx.Invoke("elasticstack:index/elasticsearchIngestProcessorDate:ElasticsearchIngestProcessorDate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticsearchIngestProcessorDate.
type ElasticsearchIngestProcessorDateArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to get the date from.
	Field string `pulumi:"field"`
	// An array of the expected date formats.
	Formats []string `pulumi:"formats"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// The locale to use when parsing the date, relevant when parsing month names or week days.
	Locale *string `pulumi:"locale"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// The format to use when writing the date to `targetField`.
	OutputFormat *string `pulumi:"outputFormat"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field that will hold the parsed date.
	TargetField *string `pulumi:"targetField"`
	// The timezone to use when parsing the date.
	Timezone *string `pulumi:"timezone"`
}

// A collection of values returned by ElasticsearchIngestProcessorDate.
type ElasticsearchIngestProcessorDateResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to get the date from.
	Field string `pulumi:"field"`
	// An array of the expected date formats.
	Formats []string `pulumi:"formats"`
	// Internal identifier of the resource
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// The locale to use when parsing the date, relevant when parsing month names or week days.
	Locale *string `pulumi:"locale"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// The format to use when writing the date to `targetField`.
	OutputFormat *string `pulumi:"outputFormat"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field that will hold the parsed date.
	TargetField *string `pulumi:"targetField"`
	// The timezone to use when parsing the date.
	Timezone *string `pulumi:"timezone"`
}

func ElasticsearchIngestProcessorDateOutput(ctx *pulumi.Context, args ElasticsearchIngestProcessorDateOutputArgs, opts ...pulumi.InvokeOption) ElasticsearchIngestProcessorDateResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticsearchIngestProcessorDateResult, error) {
			args := v.(ElasticsearchIngestProcessorDateArgs)
			r, err := ElasticsearchIngestProcessorDate(ctx, &args, opts...)
			return *r, err
		}).(ElasticsearchIngestProcessorDateResultOutput)
}

// A collection of arguments for invoking ElasticsearchIngestProcessorDate.
type ElasticsearchIngestProcessorDateOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to get the date from.
	Field pulumi.StringInput `pulumi:"field"`
	// An array of the expected date formats.
	Formats pulumi.StringArrayInput `pulumi:"formats"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// The locale to use when parsing the date, relevant when parsing month names or week days.
	Locale pulumi.StringPtrInput `pulumi:"locale"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// The format to use when writing the date to `targetField`.
	OutputFormat pulumi.StringPtrInput `pulumi:"outputFormat"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The field that will hold the parsed date.
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
	// The timezone to use when parsing the date.
	Timezone pulumi.StringPtrInput `pulumi:"timezone"`
}

func (ElasticsearchIngestProcessorDateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorDateArgs)(nil)).Elem()
}

// A collection of values returned by ElasticsearchIngestProcessorDate.
type ElasticsearchIngestProcessorDateResultOutput struct{ *pulumi.OutputState }

func (ElasticsearchIngestProcessorDateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorDateResult)(nil)).Elem()
}

func (o ElasticsearchIngestProcessorDateResultOutput) ToElasticsearchIngestProcessorDateResultOutput() ElasticsearchIngestProcessorDateResultOutput {
	return o
}

func (o ElasticsearchIngestProcessorDateResultOutput) ToElasticsearchIngestProcessorDateResultOutputWithContext(ctx context.Context) ElasticsearchIngestProcessorDateResultOutput {
	return o
}

// Description of the processor.
func (o ElasticsearchIngestProcessorDateResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to get the date from.
func (o ElasticsearchIngestProcessorDateResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) string { return v.Field }).(pulumi.StringOutput)
}

// An array of the expected date formats.
func (o ElasticsearchIngestProcessorDateResultOutput) Formats() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) []string { return v.Formats }).(pulumi.StringArrayOutput)
}

// Internal identifier of the resource
func (o ElasticsearchIngestProcessorDateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticsearchIngestProcessorDateResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticsearchIngestProcessorDateResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticsearchIngestProcessorDateResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) string { return v.Json }).(pulumi.StringOutput)
}

// The locale to use when parsing the date, relevant when parsing month names or week days.
func (o ElasticsearchIngestProcessorDateResultOutput) Locale() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) *string { return v.Locale }).(pulumi.StringPtrOutput)
}

// Handle failures for the processor.
func (o ElasticsearchIngestProcessorDateResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// The format to use when writing the date to `targetField`.
func (o ElasticsearchIngestProcessorDateResultOutput) OutputFormat() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) *string { return v.OutputFormat }).(pulumi.StringPtrOutput)
}

// Identifier for the processor.
func (o ElasticsearchIngestProcessorDateResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The field that will hold the parsed date.
func (o ElasticsearchIngestProcessorDateResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

// The timezone to use when parsing the date.
func (o ElasticsearchIngestProcessorDateResultOutput) Timezone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorDateResult) *string { return v.Timezone }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticsearchIngestProcessorDateResultOutput{})
}
