// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Converts a string field by applying a regular expression and a replacement. If the field is an array of string, all members of the array will be converted. If any non-string values are encountered, the processor will throw an exception.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/gsub-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		gsub, err := elasticstack.ElasticsearchIngestProcessorGsub(ctx, &ElasticsearchIngestProcessorGsubArgs{
// 			Field:       "field1",
// 			Pattern:     "\\.",
// 			Replacement: "-",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		_, err = elasticstack.NewElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticsearchIngestPipelineArgs{
// 			Processors: pulumi.StringArray{
// 				pulumi.String(gsub.Json),
// 			},
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func ElasticsearchIngestProcessorGsub(ctx *pulumi.Context, args *ElasticsearchIngestProcessorGsubArgs, opts ...pulumi.InvokeOption) (*ElasticsearchIngestProcessorGsubResult, error) {
	var rv ElasticsearchIngestProcessorGsubResult
	err := ctx.Invoke("elasticstack:index/elasticsearchIngestProcessorGsub:ElasticsearchIngestProcessorGsub", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticsearchIngestProcessorGsub.
type ElasticsearchIngestProcessorGsubArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to apply the replacement to.
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// The pattern to be replaced.
	Pattern string `pulumi:"pattern"`
	// The string to replace the matching patterns with.
	Replacement string `pulumi:"replacement"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

// A collection of values returned by ElasticsearchIngestProcessorGsub.
type ElasticsearchIngestProcessorGsubResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to apply the replacement to.
	Field string `pulumi:"field"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// The pattern to be replaced.
	Pattern string `pulumi:"pattern"`
	// The string to replace the matching patterns with.
	Replacement string `pulumi:"replacement"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

func ElasticsearchIngestProcessorGsubOutput(ctx *pulumi.Context, args ElasticsearchIngestProcessorGsubOutputArgs, opts ...pulumi.InvokeOption) ElasticsearchIngestProcessorGsubResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticsearchIngestProcessorGsubResult, error) {
			args := v.(ElasticsearchIngestProcessorGsubArgs)
			r, err := ElasticsearchIngestProcessorGsub(ctx, &args, opts...)
			return *r, err
		}).(ElasticsearchIngestProcessorGsubResultOutput)
}

// A collection of arguments for invoking ElasticsearchIngestProcessorGsub.
type ElasticsearchIngestProcessorGsubOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to apply the replacement to.
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// The pattern to be replaced.
	Pattern pulumi.StringInput `pulumi:"pattern"`
	// The string to replace the matching patterns with.
	Replacement pulumi.StringInput `pulumi:"replacement"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
}

func (ElasticsearchIngestProcessorGsubOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorGsubArgs)(nil)).Elem()
}

// A collection of values returned by ElasticsearchIngestProcessorGsub.
type ElasticsearchIngestProcessorGsubResultOutput struct{ *pulumi.OutputState }

func (ElasticsearchIngestProcessorGsubResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorGsubResult)(nil)).Elem()
}

func (o ElasticsearchIngestProcessorGsubResultOutput) ToElasticsearchIngestProcessorGsubResultOutput() ElasticsearchIngestProcessorGsubResultOutput {
	return o
}

func (o ElasticsearchIngestProcessorGsubResultOutput) ToElasticsearchIngestProcessorGsubResultOutputWithContext(ctx context.Context) ElasticsearchIngestProcessorGsubResultOutput {
	return o
}

// Description of the processor.
func (o ElasticsearchIngestProcessorGsubResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to apply the replacement to.
func (o ElasticsearchIngestProcessorGsubResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource.
func (o ElasticsearchIngestProcessorGsubResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticsearchIngestProcessorGsubResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticsearchIngestProcessorGsubResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o ElasticsearchIngestProcessorGsubResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticsearchIngestProcessorGsubResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o ElasticsearchIngestProcessorGsubResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// The pattern to be replaced.
func (o ElasticsearchIngestProcessorGsubResultOutput) Pattern() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) string { return v.Pattern }).(pulumi.StringOutput)
}

// The string to replace the matching patterns with.
func (o ElasticsearchIngestProcessorGsubResultOutput) Replacement() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) string { return v.Replacement }).(pulumi.StringOutput)
}

// Identifier for the processor.
func (o ElasticsearchIngestProcessorGsubResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The field to assign the converted value to, by default `field` is updated in-place.
func (o ElasticsearchIngestProcessorGsubResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorGsubResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticsearchIngestProcessorGsubResultOutput{})
}
