// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Helper data source to which can be used to create a processor to compute the Community ID for network flow data as defined in the [Community ID Specification](https://github.com/corelight/community-id-spec).
// You can use a community ID to correlate network events related to a single flow.
//
// The community ID processor reads network flow data from related [Elastic Common Schema (ECS)](https://www.elastic.co/guide/en/ecs/1.12) fields by default. If you use the ECS, no configuration is required.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/community-id-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		community, err := elasticstack.ElasticsearchIngestProcessorCommunityId(ctx, nil, nil)
// 		if err != nil {
// 			return err
// 		}
// 		_, err = elasticstack.NewElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticsearchIngestPipelineArgs{
// 			Processors: pulumi.StringArray{
// 				pulumi.String(community.Json),
// 			},
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func ElasticsearchIngestProcessorCommunityId(ctx *pulumi.Context, args *ElasticsearchIngestProcessorCommunityIdArgs, opts ...pulumi.InvokeOption) (*ElasticsearchIngestProcessorCommunityIdResult, error) {
	var rv ElasticsearchIngestProcessorCommunityIdResult
	err := ctx.Invoke("elasticstack:index/elasticsearchIngestProcessorCommunityId:ElasticsearchIngestProcessorCommunityId", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticsearchIngestProcessorCommunityId.
type ElasticsearchIngestProcessorCommunityIdArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Field containing the destination IP address.
	DestinationIp *string `pulumi:"destinationIp"`
	// Field containing the destination port.
	DestinationPort *int `pulumi:"destinationPort"`
	// Field containing the IANA number.
	IanaNumber *int `pulumi:"ianaNumber"`
	// Field containing the ICMP code.
	IcmpCode *int `pulumi:"icmpCode"`
	// Field containing the ICMP type.
	IcmpType *int `pulumi:"icmpType"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Seed for the community ID hash. Must be between 0 and 65535 (inclusive). The seed can prevent hash collisions between network domains, such as a staging and production network that use the same addressing scheme.
	Seed *int `pulumi:"seed"`
	// Field containing the source IP address.
	SourceIp *string `pulumi:"sourceIp"`
	// Field containing the source port.
	SourcePort *int `pulumi:"sourcePort"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// Output field for the community ID.
	TargetField *string `pulumi:"targetField"`
	// Field containing the transport protocol. Used only when the `ianaNumber` field is not present.
	Transport *string `pulumi:"transport"`
}

// A collection of values returned by ElasticsearchIngestProcessorCommunityId.
type ElasticsearchIngestProcessorCommunityIdResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// Field containing the destination IP address.
	DestinationIp *string `pulumi:"destinationIp"`
	// Field containing the destination port.
	DestinationPort *int `pulumi:"destinationPort"`
	// Field containing the IANA number.
	IanaNumber *int `pulumi:"ianaNumber"`
	// Field containing the ICMP code.
	IcmpCode *int `pulumi:"icmpCode"`
	// Field containing the ICMP type.
	IcmpType *int `pulumi:"icmpType"`
	// Internal identifier of the resource
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Seed for the community ID hash. Must be between 0 and 65535 (inclusive). The seed can prevent hash collisions between network domains, such as a staging and production network that use the same addressing scheme.
	Seed *int `pulumi:"seed"`
	// Field containing the source IP address.
	SourceIp *string `pulumi:"sourceIp"`
	// Field containing the source port.
	SourcePort *int `pulumi:"sourcePort"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// Output field for the community ID.
	TargetField *string `pulumi:"targetField"`
	// Field containing the transport protocol. Used only when the `ianaNumber` field is not present.
	Transport *string `pulumi:"transport"`
}

func ElasticsearchIngestProcessorCommunityIdOutput(ctx *pulumi.Context, args ElasticsearchIngestProcessorCommunityIdOutputArgs, opts ...pulumi.InvokeOption) ElasticsearchIngestProcessorCommunityIdResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticsearchIngestProcessorCommunityIdResult, error) {
			args := v.(ElasticsearchIngestProcessorCommunityIdArgs)
			r, err := ElasticsearchIngestProcessorCommunityId(ctx, &args, opts...)
			return *r, err
		}).(ElasticsearchIngestProcessorCommunityIdResultOutput)
}

// A collection of arguments for invoking ElasticsearchIngestProcessorCommunityId.
type ElasticsearchIngestProcessorCommunityIdOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// Field containing the destination IP address.
	DestinationIp pulumi.StringPtrInput `pulumi:"destinationIp"`
	// Field containing the destination port.
	DestinationPort pulumi.IntPtrInput `pulumi:"destinationPort"`
	// Field containing the IANA number.
	IanaNumber pulumi.IntPtrInput `pulumi:"ianaNumber"`
	// Field containing the ICMP code.
	IcmpCode pulumi.IntPtrInput `pulumi:"icmpCode"`
	// Field containing the ICMP type.
	IcmpType pulumi.IntPtrInput `pulumi:"icmpType"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Seed for the community ID hash. Must be between 0 and 65535 (inclusive). The seed can prevent hash collisions between network domains, such as a staging and production network that use the same addressing scheme.
	Seed pulumi.IntPtrInput `pulumi:"seed"`
	// Field containing the source IP address.
	SourceIp pulumi.StringPtrInput `pulumi:"sourceIp"`
	// Field containing the source port.
	SourcePort pulumi.IntPtrInput `pulumi:"sourcePort"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// Output field for the community ID.
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
	// Field containing the transport protocol. Used only when the `ianaNumber` field is not present.
	Transport pulumi.StringPtrInput `pulumi:"transport"`
}

func (ElasticsearchIngestProcessorCommunityIdOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorCommunityIdArgs)(nil)).Elem()
}

// A collection of values returned by ElasticsearchIngestProcessorCommunityId.
type ElasticsearchIngestProcessorCommunityIdResultOutput struct{ *pulumi.OutputState }

func (ElasticsearchIngestProcessorCommunityIdResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorCommunityIdResult)(nil)).Elem()
}

func (o ElasticsearchIngestProcessorCommunityIdResultOutput) ToElasticsearchIngestProcessorCommunityIdResultOutput() ElasticsearchIngestProcessorCommunityIdResultOutput {
	return o
}

func (o ElasticsearchIngestProcessorCommunityIdResultOutput) ToElasticsearchIngestProcessorCommunityIdResultOutputWithContext(ctx context.Context) ElasticsearchIngestProcessorCommunityIdResultOutput {
	return o
}

// Description of the processor.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// Field containing the destination IP address.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) DestinationIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *string { return v.DestinationIp }).(pulumi.StringPtrOutput)
}

// Field containing the destination port.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) DestinationPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *int { return v.DestinationPort }).(pulumi.IntPtrOutput)
}

// Field containing the IANA number.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) IanaNumber() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *int { return v.IanaNumber }).(pulumi.IntPtrOutput)
}

// Field containing the ICMP code.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) IcmpCode() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *int { return v.IcmpCode }).(pulumi.IntPtrOutput)
}

// Field containing the ICMP type.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) IcmpType() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *int { return v.IcmpType }).(pulumi.IntPtrOutput)
}

// Internal identifier of the resource
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Seed for the community ID hash. Must be between 0 and 65535 (inclusive). The seed can prevent hash collisions between network domains, such as a staging and production network that use the same addressing scheme.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) Seed() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *int { return v.Seed }).(pulumi.IntPtrOutput)
}

// Field containing the source IP address.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) SourceIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *string { return v.SourceIp }).(pulumi.StringPtrOutput)
}

// Field containing the source port.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) SourcePort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *int { return v.SourcePort }).(pulumi.IntPtrOutput)
}

// Identifier for the processor.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// Output field for the community ID.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

// Field containing the transport protocol. Used only when the `ianaNumber` field is not present.
func (o ElasticsearchIngestProcessorCommunityIdResultOutput) Transport() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorCommunityIdResult) *string { return v.Transport }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticsearchIngestProcessorCommunityIdResultOutput{})
}
