// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Splits a field into an array using a separator character. Only works on string fields.
//
// See: https://www.elastic.co/guide/en/elasticsearch/reference/current/split-processor.html
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-elasticstack/sdk/go/elasticstack"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		split, err := elasticstack.ElasticsearchIngestProcessorSplit(ctx, &ElasticsearchIngestProcessorSplitArgs{
// 			Field:     "my_field",
// 			Separator: "\\s+",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		_, err = elasticstack.NewElasticsearchIngestPipeline(ctx, "myIngestPipeline", &elasticstack.ElasticsearchIngestPipelineArgs{
// 			Processors: pulumi.StringArray{
// 				pulumi.String(split.Json),
// 			},
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func ElasticsearchIngestProcessorSplit(ctx *pulumi.Context, args *ElasticsearchIngestProcessorSplitArgs, opts ...pulumi.InvokeOption) (*ElasticsearchIngestProcessorSplitResult, error) {
	var rv ElasticsearchIngestProcessorSplitResult
	err := ctx.Invoke("elasticstack:index/elasticsearchIngestProcessorSplit:ElasticsearchIngestProcessorSplit", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ElasticsearchIngestProcessorSplit.
type ElasticsearchIngestProcessorSplitArgs struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to split
	Field string `pulumi:"field"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Preserves empty trailing fields, if any.
	PreserveTrailing *bool `pulumi:"preserveTrailing"`
	// A regex which matches the separator, eg `,` or `\s+`
	Separator string `pulumi:"separator"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

// A collection of values returned by ElasticsearchIngestProcessorSplit.
type ElasticsearchIngestProcessorSplitResult struct {
	// Description of the processor.
	Description *string `pulumi:"description"`
	// The field to split
	Field string `pulumi:"field"`
	// Internal identifier of the resource.
	Id string `pulumi:"id"`
	// Conditionally execute the processor
	If *string `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure *bool `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing *bool `pulumi:"ignoreMissing"`
	// JSON representation of this data source.
	Json string `pulumi:"json"`
	// Handle failures for the processor.
	OnFailures []string `pulumi:"onFailures"`
	// Preserves empty trailing fields, if any.
	PreserveTrailing *bool `pulumi:"preserveTrailing"`
	// A regex which matches the separator, eg `,` or `\s+`
	Separator string `pulumi:"separator"`
	// Identifier for the processor.
	Tag *string `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField *string `pulumi:"targetField"`
}

func ElasticsearchIngestProcessorSplitOutput(ctx *pulumi.Context, args ElasticsearchIngestProcessorSplitOutputArgs, opts ...pulumi.InvokeOption) ElasticsearchIngestProcessorSplitResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ElasticsearchIngestProcessorSplitResult, error) {
			args := v.(ElasticsearchIngestProcessorSplitArgs)
			r, err := ElasticsearchIngestProcessorSplit(ctx, &args, opts...)
			return *r, err
		}).(ElasticsearchIngestProcessorSplitResultOutput)
}

// A collection of arguments for invoking ElasticsearchIngestProcessorSplit.
type ElasticsearchIngestProcessorSplitOutputArgs struct {
	// Description of the processor.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The field to split
	Field pulumi.StringInput `pulumi:"field"`
	// Conditionally execute the processor
	If pulumi.StringPtrInput `pulumi:"if"`
	// Ignore failures for the processor.
	IgnoreFailure pulumi.BoolPtrInput `pulumi:"ignoreFailure"`
	// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
	IgnoreMissing pulumi.BoolPtrInput `pulumi:"ignoreMissing"`
	// Handle failures for the processor.
	OnFailures pulumi.StringArrayInput `pulumi:"onFailures"`
	// Preserves empty trailing fields, if any.
	PreserveTrailing pulumi.BoolPtrInput `pulumi:"preserveTrailing"`
	// A regex which matches the separator, eg `,` or `\s+`
	Separator pulumi.StringInput `pulumi:"separator"`
	// Identifier for the processor.
	Tag pulumi.StringPtrInput `pulumi:"tag"`
	// The field to assign the converted value to, by default `field` is updated in-place.
	TargetField pulumi.StringPtrInput `pulumi:"targetField"`
}

func (ElasticsearchIngestProcessorSplitOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorSplitArgs)(nil)).Elem()
}

// A collection of values returned by ElasticsearchIngestProcessorSplit.
type ElasticsearchIngestProcessorSplitResultOutput struct{ *pulumi.OutputState }

func (ElasticsearchIngestProcessorSplitResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ElasticsearchIngestProcessorSplitResult)(nil)).Elem()
}

func (o ElasticsearchIngestProcessorSplitResultOutput) ToElasticsearchIngestProcessorSplitResultOutput() ElasticsearchIngestProcessorSplitResultOutput {
	return o
}

func (o ElasticsearchIngestProcessorSplitResultOutput) ToElasticsearchIngestProcessorSplitResultOutputWithContext(ctx context.Context) ElasticsearchIngestProcessorSplitResultOutput {
	return o
}

// Description of the processor.
func (o ElasticsearchIngestProcessorSplitResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The field to split
func (o ElasticsearchIngestProcessorSplitResultOutput) Field() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) string { return v.Field }).(pulumi.StringOutput)
}

// Internal identifier of the resource.
func (o ElasticsearchIngestProcessorSplitResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) string { return v.Id }).(pulumi.StringOutput)
}

// Conditionally execute the processor
func (o ElasticsearchIngestProcessorSplitResultOutput) If() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) *string { return v.If }).(pulumi.StringPtrOutput)
}

// Ignore failures for the processor.
func (o ElasticsearchIngestProcessorSplitResultOutput) IgnoreFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) *bool { return v.IgnoreFailure }).(pulumi.BoolPtrOutput)
}

// If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document.
func (o ElasticsearchIngestProcessorSplitResultOutput) IgnoreMissing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) *bool { return v.IgnoreMissing }).(pulumi.BoolPtrOutput)
}

// JSON representation of this data source.
func (o ElasticsearchIngestProcessorSplitResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) string { return v.Json }).(pulumi.StringOutput)
}

// Handle failures for the processor.
func (o ElasticsearchIngestProcessorSplitResultOutput) OnFailures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) []string { return v.OnFailures }).(pulumi.StringArrayOutput)
}

// Preserves empty trailing fields, if any.
func (o ElasticsearchIngestProcessorSplitResultOutput) PreserveTrailing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) *bool { return v.PreserveTrailing }).(pulumi.BoolPtrOutput)
}

// A regex which matches the separator, eg `,` or `\s+`
func (o ElasticsearchIngestProcessorSplitResultOutput) Separator() pulumi.StringOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) string { return v.Separator }).(pulumi.StringOutput)
}

// Identifier for the processor.
func (o ElasticsearchIngestProcessorSplitResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

// The field to assign the converted value to, by default `field` is updated in-place.
func (o ElasticsearchIngestProcessorSplitResultOutput) TargetField() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ElasticsearchIngestProcessorSplitResult) *string { return v.TargetField }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ElasticsearchIngestProcessorSplitResultOutput{})
}
