// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package elasticstack

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "elasticstack:index/elasticsearchClusterSettings:ElasticsearchClusterSettings":
		r = &ElasticsearchClusterSettings{}
	case "elasticstack:index/elasticsearchComponentTemplate:ElasticsearchComponentTemplate":
		r = &ElasticsearchComponentTemplate{}
	case "elasticstack:index/elasticsearchDataStream:ElasticsearchDataStream":
		r = &ElasticsearchDataStream{}
	case "elasticstack:index/elasticsearchIndex:ElasticsearchIndex":
		r = &ElasticsearchIndex{}
	case "elasticstack:index/elasticsearchIndexLifecycle:ElasticsearchIndexLifecycle":
		r = &ElasticsearchIndexLifecycle{}
	case "elasticstack:index/elasticsearchIndexTemplate:ElasticsearchIndexTemplate":
		r = &ElasticsearchIndexTemplate{}
	case "elasticstack:index/elasticsearchIngestPipeline:ElasticsearchIngestPipeline":
		r = &ElasticsearchIngestPipeline{}
	case "elasticstack:index/elasticsearchSecurityRole:ElasticsearchSecurityRole":
		r = &ElasticsearchSecurityRole{}
	case "elasticstack:index/elasticsearchSecurityUser:ElasticsearchSecurityUser":
		r = &ElasticsearchSecurityUser{}
	case "elasticstack:index/elasticsearchSnapshotLifecycle:ElasticsearchSnapshotLifecycle":
		r = &ElasticsearchSnapshotLifecycle{}
	case "elasticstack:index/elasticsearchSnapshotRepository:ElasticsearchSnapshotRepository":
		r = &ElasticsearchSnapshotRepository{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:elasticstack" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := PkgVersion()
	if err != nil {
		fmt.Printf("failed to determine package version. defaulting to v1: %v\n", err)
	}
	pulumi.RegisterResourceModule(
		"elasticstack",
		"index/elasticsearchClusterSettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"elasticstack",
		"index/elasticsearchComponentTemplate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"elasticstack",
		"index/elasticsearchDataStream",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"elasticstack",
		"index/elasticsearchIndex",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"elasticstack",
		"index/elasticsearchIndexLifecycle",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"elasticstack",
		"index/elasticsearchIndexTemplate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"elasticstack",
		"index/elasticsearchIngestPipeline",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"elasticstack",
		"index/elasticsearchSecurityRole",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"elasticstack",
		"index/elasticsearchSecurityUser",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"elasticstack",
		"index/elasticsearchSnapshotLifecycle",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"elasticstack",
		"index/elasticsearchSnapshotRepository",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"elasticstack",
		&pkg{version},
	)
}
