// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Sets one field and associates it with the specified value. If the field already exists, its value will be replaced with the provided one.
 *
 * See: https://www.elastic.co/guide/en/elasticsearch/reference/current/set-processor.html
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as elasticstack from "@pulumi/elasticstack";
 *
 * const set = elasticstack.ElasticsearchIngestProcessorSet({
 *     field: "count",
 *     value: 1,
 * });
 * const myIngestPipeline = new elasticstack.ElasticsearchIngestPipeline("myIngestPipeline", {processors: [set.then(set => set.json)]});
 * ```
 */
export function elasticsearchIngestProcessorSet(args: ElasticsearchIngestProcessorSetArgs, opts?: pulumi.InvokeOptions): Promise<ElasticsearchIngestProcessorSetResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("elasticstack:index/elasticsearchIngestProcessorSet:ElasticsearchIngestProcessorSet", {
        "copyFrom": args.copyFrom,
        "description": args.description,
        "field": args.field,
        "if": args.if,
        "ignoreEmptyValue": args.ignoreEmptyValue,
        "ignoreFailure": args.ignoreFailure,
        "mediaType": args.mediaType,
        "onFailures": args.onFailures,
        "override": args.override,
        "tag": args.tag,
        "value": args.value,
    }, opts);
}

/**
 * A collection of arguments for invoking ElasticsearchIngestProcessorSet.
 */
export interface ElasticsearchIngestProcessorSetArgs {
    /**
     * The origin field which will be copied to `field`, cannot set `value` simultaneously.
     */
    copyFrom?: string;
    /**
     * Description of the processor.
     */
    description?: string;
    /**
     * The field to insert, upsert, or update.
     */
    field: string;
    /**
     * Conditionally execute the processor
     */
    if?: string;
    /**
     * If `true` and `value` is a template snippet that evaluates to `null` or the empty string, the processor quietly exits without modifying the document
     */
    ignoreEmptyValue?: boolean;
    /**
     * Ignore failures for the processor.
     */
    ignoreFailure?: boolean;
    /**
     * The media type for encoding value.
     */
    mediaType?: string;
    /**
     * Handle failures for the processor.
     */
    onFailures?: string[];
    /**
     * If processor will update fields with pre-existing non-null-valued field.
     */
    override?: boolean;
    /**
     * Identifier for the processor.
     */
    tag?: string;
    /**
     * The value to be set for the field. Supports template snippets. May specify only one of `value` or `copyFrom`.
     */
    value?: string;
}

/**
 * A collection of values returned by ElasticsearchIngestProcessorSet.
 */
export interface ElasticsearchIngestProcessorSetResult {
    /**
     * The origin field which will be copied to `field`, cannot set `value` simultaneously.
     */
    readonly copyFrom?: string;
    /**
     * Description of the processor.
     */
    readonly description?: string;
    /**
     * The field to insert, upsert, or update.
     */
    readonly field: string;
    /**
     * Internal identifier of the resource.
     */
    readonly id: string;
    /**
     * Conditionally execute the processor
     */
    readonly if?: string;
    /**
     * If `true` and `value` is a template snippet that evaluates to `null` or the empty string, the processor quietly exits without modifying the document
     */
    readonly ignoreEmptyValue?: boolean;
    /**
     * Ignore failures for the processor.
     */
    readonly ignoreFailure?: boolean;
    /**
     * JSON representation of this data source.
     */
    readonly json: string;
    /**
     * The media type for encoding value.
     */
    readonly mediaType?: string;
    /**
     * Handle failures for the processor.
     */
    readonly onFailures?: string[];
    /**
     * If processor will update fields with pre-existing non-null-valued field.
     */
    readonly override?: boolean;
    /**
     * Identifier for the processor.
     */
    readonly tag?: string;
    /**
     * The value to be set for the field. Supports template snippets. May specify only one of `value` or `copyFrom`.
     */
    readonly value?: string;
}

export function elasticsearchIngestProcessorSetOutput(args: ElasticsearchIngestProcessorSetOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<ElasticsearchIngestProcessorSetResult> {
    return pulumi.output(args).apply(a => elasticsearchIngestProcessorSet(a, opts))
}

/**
 * A collection of arguments for invoking ElasticsearchIngestProcessorSet.
 */
export interface ElasticsearchIngestProcessorSetOutputArgs {
    /**
     * The origin field which will be copied to `field`, cannot set `value` simultaneously.
     */
    copyFrom?: pulumi.Input<string>;
    /**
     * Description of the processor.
     */
    description?: pulumi.Input<string>;
    /**
     * The field to insert, upsert, or update.
     */
    field: pulumi.Input<string>;
    /**
     * Conditionally execute the processor
     */
    if?: pulumi.Input<string>;
    /**
     * If `true` and `value` is a template snippet that evaluates to `null` or the empty string, the processor quietly exits without modifying the document
     */
    ignoreEmptyValue?: pulumi.Input<boolean>;
    /**
     * Ignore failures for the processor.
     */
    ignoreFailure?: pulumi.Input<boolean>;
    /**
     * The media type for encoding value.
     */
    mediaType?: pulumi.Input<string>;
    /**
     * Handle failures for the processor.
     */
    onFailures?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * If processor will update fields with pre-existing non-null-valued field.
     */
    override?: pulumi.Input<boolean>;
    /**
     * Identifier for the processor.
     */
    tag?: pulumi.Input<string>;
    /**
     * The value to be set for the field. Supports template snippets. May specify only one of `value` or `copyFrom`.
     */
    value?: pulumi.Input<string>;
}
