// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * ## Import
 *
 * ```sh
 *  $ pulumi import elasticstack:index/elasticsearchIngestPipeline:ElasticsearchIngestPipeline my_ingest_pipeline <cluster_uuid>/<ingest pipeline name>
 * ```
 */
export class ElasticsearchIngestPipeline extends pulumi.CustomResource {
    /**
     * Get an existing ElasticsearchIngestPipeline resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ElasticsearchIngestPipelineState, opts?: pulumi.CustomResourceOptions): ElasticsearchIngestPipeline {
        return new ElasticsearchIngestPipeline(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'elasticstack:index/elasticsearchIngestPipeline:ElasticsearchIngestPipeline';

    /**
     * Returns true if the given object is an instance of ElasticsearchIngestPipeline.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ElasticsearchIngestPipeline {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ElasticsearchIngestPipeline.__pulumiType;
    }

    /**
     * Description of the ingest pipeline.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Used to establish connection to Elasticsearch server. Overrides environment variables if present.
     */
    public readonly elasticsearchConnection!: pulumi.Output<outputs.ElasticsearchIngestPipelineElasticsearchConnection | undefined>;
    /**
     * Internal identifier of the resource
     */
    public /*out*/ readonly id!: pulumi.Output<string>;
    /**
     * Optional user metadata about the index template.
     */
    public readonly metadata!: pulumi.Output<string | undefined>;
    /**
     * The name of the ingest pipeline.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Processors to run immediately after a processor failure. Each processor supports a processor-level `onFailure` value. If a processor without an `onFailure` value fails, Elasticsearch uses this pipeline-level parameter as a fallback. The processors in this parameter run sequentially in the order specified. Elasticsearch will not attempt to run the pipeline’s remaining processors. See: https://www.elastic.co/guide/en/elasticsearch/reference/current/processors.html. Each record must be a valid JSON document
     */
    public readonly onFailures!: pulumi.Output<string[] | undefined>;
    /**
     * Processors used to perform transformations on documents before indexing. Processors run sequentially in the order specified. See: https://www.elastic.co/guide/en/elasticsearch/reference/current/processors.html. Each record must be a valid JSON document.
     */
    public readonly processors!: pulumi.Output<string[]>;

    /**
     * Create a ElasticsearchIngestPipeline resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ElasticsearchIngestPipelineArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ElasticsearchIngestPipelineArgs | ElasticsearchIngestPipelineState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ElasticsearchIngestPipelineState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["elasticsearchConnection"] = state ? state.elasticsearchConnection : undefined;
            resourceInputs["id"] = state ? state.id : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["onFailures"] = state ? state.onFailures : undefined;
            resourceInputs["processors"] = state ? state.processors : undefined;
        } else {
            const args = argsOrState as ElasticsearchIngestPipelineArgs | undefined;
            if ((!args || args.processors === undefined) && !opts.urn) {
                throw new Error("Missing required property 'processors'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["elasticsearchConnection"] = args ? args.elasticsearchConnection : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["onFailures"] = args ? args.onFailures : undefined;
            resourceInputs["processors"] = args ? args.processors : undefined;
            resourceInputs["id"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ElasticsearchIngestPipeline.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ElasticsearchIngestPipeline resources.
 */
export interface ElasticsearchIngestPipelineState {
    /**
     * Description of the ingest pipeline.
     */
    description?: pulumi.Input<string>;
    /**
     * Used to establish connection to Elasticsearch server. Overrides environment variables if present.
     */
    elasticsearchConnection?: pulumi.Input<inputs.ElasticsearchIngestPipelineElasticsearchConnection>;
    /**
     * Internal identifier of the resource
     */
    id?: pulumi.Input<string>;
    /**
     * Optional user metadata about the index template.
     */
    metadata?: pulumi.Input<string>;
    /**
     * The name of the ingest pipeline.
     */
    name?: pulumi.Input<string>;
    /**
     * Processors to run immediately after a processor failure. Each processor supports a processor-level `onFailure` value. If a processor without an `onFailure` value fails, Elasticsearch uses this pipeline-level parameter as a fallback. The processors in this parameter run sequentially in the order specified. Elasticsearch will not attempt to run the pipeline’s remaining processors. See: https://www.elastic.co/guide/en/elasticsearch/reference/current/processors.html. Each record must be a valid JSON document
     */
    onFailures?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Processors used to perform transformations on documents before indexing. Processors run sequentially in the order specified. See: https://www.elastic.co/guide/en/elasticsearch/reference/current/processors.html. Each record must be a valid JSON document.
     */
    processors?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a ElasticsearchIngestPipeline resource.
 */
export interface ElasticsearchIngestPipelineArgs {
    /**
     * Description of the ingest pipeline.
     */
    description?: pulumi.Input<string>;
    /**
     * Used to establish connection to Elasticsearch server. Overrides environment variables if present.
     */
    elasticsearchConnection?: pulumi.Input<inputs.ElasticsearchIngestPipelineElasticsearchConnection>;
    /**
     * Optional user metadata about the index template.
     */
    metadata?: pulumi.Input<string>;
    /**
     * The name of the ingest pipeline.
     */
    name?: pulumi.Input<string>;
    /**
     * Processors to run immediately after a processor failure. Each processor supports a processor-level `onFailure` value. If a processor without an `onFailure` value fails, Elasticsearch uses this pipeline-level parameter as a fallback. The processors in this parameter run sequentially in the order specified. Elasticsearch will not attempt to run the pipeline’s remaining processors. See: https://www.elastic.co/guide/en/elasticsearch/reference/current/processors.html. Each record must be a valid JSON document
     */
    onFailures?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Processors used to perform transformations on documents before indexing. Processors run sequentially in the order specified. See: https://www.elastic.co/guide/en/elasticsearch/reference/current/processors.html. Each record must be a valid JSON document.
     */
    processors: pulumi.Input<pulumi.Input<string>[]>;
}
